#!/usr/bin/env python3
"""Build a prose book PDF from Markdown files using Typst."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import unicodedata
from dataclasses import dataclass
from datetime import date
from pathlib import Path


PREAMBLE = """// Generated by make_story_book.py; compile with Typst.
#set document(title: {book_title}, author: {author})
#set page(paper: "a5", margin: (x: 18mm, y: 20mm), fill: rgb("{background_color}"))
#set text(font: {font}, size: 11pt, fill: rgb("{text_color}"), lang: "{language}")
#set par(justify: true, first-line-indent: 1.5em, leading: {line_spread}em)

#align(center)[
  #v(18%)
  #text(size: 28pt)[#text({book_title})]
  #v(12%)
  #text(size: 20pt)[#text({author})]
  #v(12%)
  #text({timestamp})
]
#pagebreak()
#outline(title: block(below: 3em)[תוכן עניינים])
#pagebreak()
"""


@dataclass
class Story:
    path: Path
    title: str
    paragraphs: list[str]
    pictures: list[Path]


def typst_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def sort_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    return "".join(character for character in normalized if not "\u0590" <= character <= "\u05cf").casefold()


def find_pictures(story_path: Path, title: str) -> list[Path]:
    picture_directory = story_path.parent / "pics" / title
    supported_extensions = {".jpeg", ".jpg", ".png", ".svg", ".webp"}
    if not picture_directory.is_dir():
        return []
    return sorted(
        path.resolve()
        for path in picture_directory.iterdir()
        if path.is_file() and path.suffix.lower() in supported_extensions
    )


def parse_markdown(path: Path) -> Story:
    title = ""
    paragraphs: list[str] = []
    paragraph_lines: list[str] = []

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("---"):
            break
        if line.startswith("# ") and not title:
            title = line[2:].strip()
            continue
        if line:
            paragraph_lines.append(line)
        elif paragraph_lines:
            paragraphs.append(" ".join(paragraph_lines))
            paragraph_lines = []

    if paragraph_lines:
        paragraphs.append(" ".join(paragraph_lines))
    if not title:
        raise ValueError(f"{path}: expected a '# Title' heading")
    return Story(path=path, title=title, paragraphs=paragraphs, pictures=find_pictures(path, title))


def story_typst(story: Story, project_root: Path) -> str:
    output = [f"#heading(level: 1, outlined: true)[#text({typst_string(story.title)})]", "#v(1em)"]
    for paragraph in story.paragraphs:
        output.append(f"#text({typst_string(paragraph)})")
        output.append("#parbreak()")
    if story.pictures:
        picture_paths = ["/" + picture.relative_to(project_root).as_posix() for picture in story.pictures]
        output.append("#pagebreak()")
        if len(picture_paths) == 1:
            output.extend(
                [
                    "#align(center)[",
                    f"  #image({typst_string(picture_paths[0])}, width: 82%, height: 150mm, fit: \"contain\")",
                    "]",
                ]
            )
        else:
            output.append("#grid(columns: (1fr, 1fr), gutter: 6pt,")
            for picture_path in picture_paths:
                output.append(f"  image({typst_string(picture_path)}, width: 100%, height: 75mm, fit: \"cover\"),")
            output.append(")")
    return "\n".join(output)


def load_config(path: Path) -> dict:
    config = json.loads(path.read_text(encoding="utf-8"))
    required = ("title", "author", "sources")
    missing = [key for key in required if not config.get(key)]
    if missing:
        raise ValueError(f"{path}: missing required setting(s): {', '.join(missing)}")
    return config


def find_sources(config: dict, config_path: Path) -> list[Path]:
    root = (config_path.parent / config.get("source_root", ".")).resolve()
    paths: set[Path] = set()
    for pattern in config["sources"]:
        paths.update(path for path in root.glob(pattern) if path.is_file())
    if not paths:
        raise ValueError("no Markdown files matched 'sources'")
    return sorted(paths)


def write_typst(config: dict, config_path: Path, output_path: Path) -> int:
    stories = [parse_markdown(path) for path in find_sources(config, config_path)]
    excluded = set(config.get("exclude_titles", []))
    stories = [story for story in stories if story.title not in excluded]
    stories.sort(key=lambda story: sort_text(story.title))

    language_name = config.get("language", "hebrew")
    language = {"english": "en", "hebrew": "he", "arabic": "ar"}.get(language_name, language_name)
    preamble = PREAMBLE.format(
        font=typst_string(config.get("font", "Libertinus Serif")),
        line_spread=config.get("line_spread", 1.35),
        background_color=config.get("background_color", "FFFFFF"),
        text_color=config.get("text_color", "000000"),
        language=language,
        book_title=typst_string(config["title"]),
        author=typst_string(config["author"]),
        timestamp=typst_string(config.get("date", date.today().strftime("%B, %Y"))),
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    project_root = (config_path.parent / config.get("source_root", ".")).resolve()
    chapters = "\n\n#pagebreak()\n\n".join(story_typst(story, project_root) for story in stories)
    output_path.write_text(f"{preamble}{chapters}\n", encoding="utf-8")
    return len(stories)


def compile_pdf(typst_path: Path, output_directory: Path, project_root: Path) -> Path:
    output_directory.mkdir(parents=True, exist_ok=True)
    pdf_path = output_directory / f"{typst_path.stem}.pdf"
    subprocess.run(["typst", "compile", "--root", str(project_root), str(typst_path), str(pdf_path)], check=True)
    return pdf_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a prose-book Typst file or PDF from Markdown sources.")
    parser.add_argument("config", type=Path, help="Path to a book JSON configuration file.")
    parser.add_argument("--typ", type=Path, default=Path("build/stories.typ"), help="Generated Typst path.")
    parser.add_argument("--pdf", action="store_true", help="Compile the generated Typst with typst.")
    parser.add_argument("--output-dir", type=Path, default=Path("build"), help="PDF output directory.")
    arguments = parser.parse_args()

    try:
        config_path = arguments.config.resolve()
        typst_path = arguments.typ.resolve()
        config = load_config(config_path)
        count = write_typst(config, config_path, typst_path)
        print(f"Wrote {typst_path} with {count} story/stories.")
        if arguments.pdf:
            project_root = (config_path.parent / config.get("source_root", ".")).resolve()
            pdf_path = compile_pdf(typst_path, arguments.output_dir.resolve(), project_root)
            print(f"Wrote {pdf_path}.")
    except (OSError, ValueError, json.JSONDecodeError, subprocess.CalledProcessError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())