#!/usr/bin/env python3
"""Build a poetry book PDF from Markdown files using Typst."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import unicodedata
from dataclasses import dataclass
from datetime import date
from pathlib import Path


PREAMBLE = """// Generated by make_song_book.py; compile with Typst.
#set document(title: {book_title}, author: {author})
#set page(paper: "a5", margin: (x: 18mm, y: 20mm), fill: rgb("{background_color}"))
#set text(font: {font}, size: 12pt, fill: rgb("{text_color}"), lang: "{language}")
#set par(leading: {line_spread}em)

#align(center)[
    #v(18%)
    #text(size: 28pt)[#text({book_title})]
    #v(12%)
    #text(size: 20pt)[#text({author})]
    #v(12%)
    #text({timestamp})
]
#pagebreak()
#outline(title: block(below: 3em)[Contents])
#pagebreak()
"""


@dataclass
class Poem:
    path: Path
    title: str
    blocks: list[list[str]]


def typst_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def sort_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    return "".join(character for character in normalized if not "\u0590" <= character <= "\u05cf").casefold()


def parse_markdown(path: Path) -> Poem:
    title = ""
    blocks: list[list[str]] = []
    block: list[str] = []

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("---"):
            break
        if line.startswith("# ") and not title:
            title = line[2:].rstrip("\\").strip()
            continue
        line = line.rstrip("\\").strip()
        if line:
            block.append(line)
        elif block:
            blocks.append(block)
            block = []

    if block:
        blocks.append(block)
    if not title:
        raise ValueError(f"{path}: expected a '# Title' heading")
    return Poem(path=path, title=title, blocks=blocks)


def poem_typst(poem: Poem) -> str:
    output = [f"#heading(level: 1, outlined: true)[#text({typst_string(poem.title)})]", "#v(0.75em)", "#block(width: 100%)["]
    for block in poem.blocks:
        for line in block:
            output.append(f"  #text({typst_string(line)})")
            output.append("  #linebreak()")
        output.append("  #v(0.75em)")
    output.append("]")
    return "\n".join(output)


def load_config(path: Path) -> dict:
    config = json.loads(path.read_text(encoding="utf-8"))
    required = ("title", "author", "sources")
    missing = [key for key in required if not config.get(key)]
    if missing:
        raise ValueError(f"{path}: missing required setting(s): {', '.join(missing)}")
    return config


def find_sources(config: dict, config_path: Path) -> list[Path]:
    root = (config_path.parent / config.get("source_root", ".")).resolve()
    paths: set[Path] = set()
    for pattern in config["sources"]:
        paths.update(path for path in root.glob(pattern) if path.is_file())
    if not paths:
        raise ValueError("no Markdown files matched 'sources'")
    return sorted(paths)


def write_typst(config: dict, config_path: Path, output_path: Path) -> int:
    poems = [parse_markdown(path) for path in find_sources(config, config_path)]
    excluded = set(config.get("exclude_titles", []))
    poems = [poem for poem in poems if poem.title not in excluded]
    poems.sort(key=lambda poem: sort_text(poem.title))

    language = {"english": "en", "hebrew": "he", "arabic": "ar"}.get(config.get("language", "english"), config["language"])
    preamble = PREAMBLE.format(
        font=typst_string(config.get("font", "Linden Hill")),
        line_spread=config.get("line_spread", 1.10344),
        background_color=config.get("background_color", "FFFFFF"),
        text_color=config.get("text_color", "000000"),
        language=language,
        book_title=typst_string(config["title"]),
        author=typst_string(config["author"]),
        timestamp=typst_string(config.get("date", date.today().strftime("%B, %Y"))),
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    chapters = "\n\n#pagebreak()\n\n".join(poem_typst(poem) for poem in poems)
    output_path.write_text(f"{preamble}{chapters}\n", encoding="utf-8")
    return len(poems)


def compile_pdf(typst_path: Path, output_directory: Path) -> Path:
    output_directory.mkdir(parents=True, exist_ok=True)
    pdf_path = output_directory / f"{typst_path.stem}.pdf"
    subprocess.run(["typst", "compile", str(typst_path), str(pdf_path)], check=True)
    return pdf_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a poetry-book Typst file or PDF from Markdown sources.")
    parser.add_argument("config", type=Path, help="Path to a book JSON configuration file.")
    parser.add_argument("--typ", type=Path, default=Path("build/book.typ"), help="Generated Typst path.")
    parser.add_argument("--pdf", action="store_true", help="Compile the generated Typst with typst.")
    parser.add_argument("--output-dir", type=Path, default=Path("build"), help="PDF output directory.")
    arguments = parser.parse_args()

    try:
        config_path = arguments.config.resolve()
        typst_path = arguments.typ.resolve()
        count = write_typst(load_config(config_path), config_path, typst_path)
        print(f"Wrote {typst_path} with {count} chapter(s).")
        if arguments.pdf:
            pdf_path = compile_pdf(typst_path, arguments.output_dir.resolve())
            print(f"Wrote {pdf_path}.")
    except (OSError, ValueError, json.JSONDecodeError, subprocess.CalledProcessError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())